#include "../runtime/matchmaking_policy.h"

#include <assert.h>
#include <string.h>

int main() {
  static_assert(coop_matchmaking::kMemberLimit == 4, "four-player lobby limit changed");
  static_assert(coop_matchmaking::kPublicLobbyType == 2, "Steam public lobby value changed");
  static_assert(coop_matchmaking::kInvisibleLobbyType == 3, "Steam invisible lobby value changed");
  assert(strcmp(coop_matchmaking::kProtocolKey, "dr2_4p_protocol") == 0);
  assert(coop_matchmaking::IsCompatible("4"));
  assert(!coop_matchmaking::IsCompatible(nullptr));
  assert(!coop_matchmaking::IsCompatible(""));
  assert(!coop_matchmaking::IsCompatible("0"));
  assert(!coop_matchmaking::IsCompatible("1"));
  assert(!coop_matchmaking::IsCompatible("2"));
  assert(!coop_matchmaking::IsCompatible("3"));
  static_assert(coop_matchmaking::kFriendsSetRichPresenceSlot == 37, "SteamFriends014 ABI changed");
  static_assert(coop_matchmaking::kFriendsGetFriendRichPresenceSlot == 39, "SteamFriends014 ABI changed");
  static_assert(coop_matchmaking::kFriendsRequestFriendRichPresenceSlot == 42, "SteamFriends014 ABI changed");
  static_assert(coop_matchmaking::kAppsBIsDlcInstalledSlot == 7, "SteamApps006 ABI changed");
  static_assert(coop_matchmaking::kAppsBGetDlcDataByIndexSlot == 11, "SteamApps006 ABI changed");
  assert(coop_matchmaking::IsMissing(nullptr));
  assert(coop_matchmaking::IsMissing(""));
  assert(!coop_matchmaking::IsMissing("0"));
  assert(!coop_matchmaking::IsMissing("4"));
  assert(coop_matchmaking::HasPeerProof("4", nullptr));
  assert(coop_matchmaking::HasPeerProof(nullptr, "4"));
  assert(coop_matchmaking::HasPeerProof("", "4"));
  assert(!coop_matchmaking::HasPeerProof(nullptr, nullptr));
  assert(!coop_matchmaking::HasPeerProof("", ""));
  assert(!coop_matchmaking::HasPeerProof("0", "4"));
  assert(!coop_matchmaking::HasPeerProof("1", "4"));
  assert(coop_matchmaking::IsDr2OptionalSkillPack(353050));
  assert(coop_matchmaking::IsDr2OptionalSkillPack(353051));
  assert(coop_matchmaking::IsDr2OptionalSkillPack(353052));
  assert(coop_matchmaking::IsDr2OptionalSkillPack(353053));
  assert(!coop_matchmaking::IsDr2OptionalSkillPack(353049));
  assert(!coop_matchmaking::IsDr2OptionalSkillPack(353054));
  assert(!coop_matchmaking::IsDr2OptionalSkillPack(45740));
  assert(coop_matchmaking::VisibleProductionLobbyType(3) == 2);
  assert(coop_matchmaking::VisibleProductionLobbyType(2) == 2);
  assert(coop_matchmaking::VisibleProductionLobbyType(1) == 1);
  assert(coop_matchmaking::VisibleProductionLobbyType(0) == 0);
  assert(!coop_matchmaking::ShouldLogAdmissionAttempt(0));
  assert(coop_matchmaking::ShouldLogAdmissionAttempt(1));
  assert(coop_matchmaking::ShouldLogAdmissionAttempt(coop_matchmaking::kAdmissionLogBurst));
  assert(!coop_matchmaking::ShouldLogAdmissionAttempt(coop_matchmaking::kAdmissionLogBurst + 1));
  assert(coop_matchmaking::ShouldLogAdmissionAttempt(coop_matchmaking::kAdmissionLogInterval));
  assert(!coop_matchmaking::ShouldLogAdmissionAttempt(coop_matchmaking::kAdmissionLogInterval + 1));
  assert(coop_matchmaking::CollectionTargetForOccupiedRemoteLinks(-1) == 2);
  assert(coop_matchmaking::CollectionTargetForOccupiedRemoteLinks(0) == 2);
  assert(coop_matchmaking::CollectionTargetForOccupiedRemoteLinks(1) == 3);
  assert(coop_matchmaking::CollectionTargetForOccupiedRemoteLinks(2) == 4);
  assert(coop_matchmaking::CollectionTargetForOccupiedRemoteLinks(3) == 4);
  assert(coop_matchmaking::CollectionTargetForAcceptedClients(0) == 2);
  assert(coop_matchmaking::CollectionTargetForAcceptedClients(1) == 2);
  assert(coop_matchmaking::CollectionTargetForAcceptedClients(2) == 3);
  assert(coop_matchmaking::CollectionTargetForAcceptedClients(3) == 4);
  assert(coop_matchmaking::CollectionTargetForAcceptedClients(4) == 4);
  assert(coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, false, 1, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(true, true, false, false, 1, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, false, false, false, 1, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, true, false, 1, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, true, 1, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, false, 3, 3, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, false, 0, 0, 2, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, false, 1, 3, 1, 0));
  assert(!coop_matchmaking::ShouldAllowConnectedJoin(false, true, false, false, 1, 3, 2, 1));
  assert(coop_matchmaking::ShouldSignalFlowForMemberCount(2, 3, true));
  assert(coop_matchmaking::ShouldSignalFlowForMemberCount(3, 4, true));
  assert(!coop_matchmaking::ShouldSignalFlowForMemberCount(2, 2, true));
  assert(!coop_matchmaking::ShouldSignalFlowForMemberCount(3, 3, true));
  assert(!coop_matchmaking::ShouldSignalFlowForMemberCount(4, 4, true));
  assert(!coop_matchmaking::ShouldSignalFlowForMemberCount(2, 5, true));
  assert(!coop_matchmaking::ShouldSignalFlowForMemberCount(2, 3, false));
  assert(coop_matchmaking::EffectiveMemberCount(3, 1) == 3);
  assert(coop_matchmaking::EffectiveMemberCount(1, 3) == 3);
  assert(coop_matchmaking::EffectiveMemberCount(3, 3) == 3);
  assert(coop_matchmaking::EffectiveMemberCount(-1, 2) == 2);
  assert(coop_matchmaking::EffectiveMemberCount(2, -1) == 2);
  assert(coop_matchmaking::EffectiveMemberCount(5, 2) == 4);
  assert(coop_matchmaking::IsRequiredProductionImport("steam_api.dll", "SteamMatchmaking"));
  assert(coop_matchmaking::IsRequiredProductionImport("steam_api.dll", "SteamFriends"));
  assert(coop_matchmaking::IsRequiredProductionImport("steam_api.dll", "SteamApps"));
  assert(coop_matchmaking::IsRequiredProductionImport("steam_api.dll", "SteamAPI_RunCallbacks"));
  assert(!coop_matchmaking::IsRequiredProductionImport("steam_api.dll", "SteamNetworking"));
  assert(!coop_matchmaking::IsRequiredProductionImport("KERNEL32.dll", "SteamMatchmaking"));
  assert(!coop_matchmaking::IsRequiredProductionImport(nullptr, "SteamMatchmaking"));
  assert(!coop_matchmaking::IsRequiredProductionImport("steam_api.dll", nullptr));
  return 0;
}
